apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: aoc-sre-hub-eastus
  namespace: aoc-sre
spec:
  baseDomain: acmdev.azure.ansiblecloud.com
  imageSetRef:
    name: img4.9.21-x86-64-appsub
  installConfigSecretTemplateRef:
    name: azure-standard-install-config
  platform:
    azure:
      baseDomainResourceGroupName: rg-core-infrastructure-dev
      credentialsSecretRef:
        name: azure-creds
      region: eastus
  pullSecretRef:
    name: ocp-pull-secret
  size: 2
