kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterdeployment-view-clusterscope-role
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - 'hive.openshift.io'
    resources:
      - clusterdeployments