kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acs-namespace-access
  namespace: acs
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: acm
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:acs'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
