kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: shared-infrastructure-admins
  - kind: ServiceAccount
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:cicd:gurnben'
  - kind: ServiceAccount
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:managedservices:gurnben'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
